name: Build Production

on: [workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Export version from package.json
        run: |
          echo ::set-env name=PACKAGE_VERSION::$(node -pe "require('./package.json').version")
      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Decode Production Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" > keystore.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.keystore.asc > android/app/keystore.keystore
      - name: Install dependencies
        run: yarn install
      - name: fastlane
        uses: maierj/fastlane-action@v1.4.0
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          BUGSNAG_APIKEY: ${{ secrets.BUGSNAG_APIKEY }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_JSON_KEY_DATA }}
        with:
          lane: 'android prod'
      - name: Upload universal apk to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: prod.apk
          path: android/app/build/outputs/apk/prod/release/app-prod-release.apk
      - name: Upload Android App Bundle to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release.aab
          path: android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
